services:
  - type: web
    name: requisicao-clientes-procer
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        generateValue: true
